spring.datasource.url=jdbc:mysql://localhost:3306/agriculture_farm

spring.datasource.username=root

spring.datasource.password=2007

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

server.port=8081